name: Decision Tree

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Train algoritm 
      run: |
        python DTree.py
    - name: Generate predictions
      uses: stefanzweifel/git-auto-commit-action@v2.3.0
      with:
        commit_message: "Prediction CSV" 
        file_pattern: \*.csv
        branch: ${{ github.head_ref }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
