name: Decision Tree

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pandas
        pip install numpy 
        pip install sklearn
    - name: Lint with flake8
      run: |
        pip install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Train algoritm 
      run: |
        python example.py
    - name: Generate predictions
      uses: stefanzweifel/git-auto-commit-action@v2.3.0
      with:
        commit_message: "Prediction CSV" 
        commit_options: '--no-verify --signoff'
        branch: ${{ github.head_ref }}
        
